PROMPT_GENERATE_MDT = """
Given the case study as a .pdf file, generate a plausible multi-disciplinary meeting transcript consisting of only the relevant specialists. There is no need to give names to each specialist, but instead refer to them by their specialty. The goal of the meeting is to eventually come up with the observations and conclusions made in the case study. Begin each meeting with the attendance of the specialists. Include a conclusion of the meeting the summarizes the general findings of the discussion. Return only the transcript with no other text.
"""

PROMPT_FACTUAL_CORRECTNESS = """
You will be given a case study in a .pdf file and a meeting transcript below. The meeting transcript is a discussion that should result in the creation of the case study. Be as strict as possible. Your task is to rate the transcript on one metric and provide appropriate feedback:

Evaluation Criteria: Factual Correctness (1-5): This is a measurement of how factually correct the generated transcript with respect to the case study. A higher score means that the transcript is completely factual, while a score of 0 means that the transcript contains multiple hallucinations not found in the case study.

Rubric: 
5 – Fully Accurate: Every factual detail in the transcript aligns precisely with the case study, with no additions, distortions, or omissions.
4 – Mostly Accurate: The transcript is largely factual with only minor discrepancies or one small omission/addition that does not alter overall understanding.
3 – Moderately Accurate: Several factual inconsistencies or omissions are present, but the core narrative remains recognizable and generally aligned with the case study.
2 – Minimally Accurate: Many factual errors, omissions, or added information not found in the case study significantly distort or misrepresent the original content.
1 – Factually Incorrect: The majority of the transcript does not reflect the case study; it includes numerous hallucinations or contradictions, making it largely unreliable.

Evaluation Steps:
1. Read the Case Study (PDF)
2. Read the Meeting Transcript
3. Compare for Factual Alignment
4. Rate on a Scale of 1 to 5 with 5 containing no discrepancies.
5. Write Feedback

Meeting Transcript:
{transcript}
"""

PROMPT_PLAUSIBILITY = """
You will be given a meeting transcript below. The meeting transcript is a discussion that should result in the creation of a case study. Be as strict as possible. However, ignore citation tokens in your evaluation. Your task is to rate the transcript on one metric and provide appropriate feedback: 

Evaluation Criteria: Plausibility (1-5): This is a measurement of how plausible the generated transcript is with respect to the case study. A higher score means that the transcript exhibits an actual conversation that human specialists made, while a score of 0 means that the transcript is most likely generated by a LLM - or conventionally, does not pass the Turing test.

5 – Highly Plausible: The transcript reads as a natural, unscripted expert conversation with realistic dynamics, clarifications, and occasional missteps; it fully resembles a real human meeting.
4 – Mostly Plausible: The transcript is generally believable with minor signs of artificiality (e.g., overly clean logic or lack of natural hesitations), but still feels like a real discussion among professionals.
3 – Moderately Plausible: The transcript includes plausible topic flow but has noticeable signs of artificial generation, such as perfectly sequential logic or repetitive phrasing, reducing believability.
2 – Barely Plausible: The transcript contains multiple unnatural elements—uniform tone, excessive agreement, or robotic transitions—that make it unlikely to be human conversation, though not entirely implausible.
1 – Not Plausible:The transcript clearly lacks realistic conversational structure, with mechanical responses, unrealistic jargon use, or a complete absence of human error or nuance.

Evaluation Steps: 
1. Read the Meeting Transcript
2. Identify Markers of Human Interaction vs. LLM Generation
3. Rate on a Scale of 1 to 5
4. Write Feedback

Meeting Transcript:
{transcript}
"""
